# -*- coding: utf-8 -*-
"""Face_recog

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9lO0tckcV1RgxV1f7Nd-DSAbhFZShf-
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')

image = cv2.imread('WhatsApp Image 2023-07-07 at 13.50.15.jpg')
# convert to rgb
img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
plt.imshow(img_rgb)

# resize the image
image = cv2.resize(image, (400, 600))

# convert to gray scale image
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
plt.imshow(gray, cmap='gray')

faces = face_cascade.detectMultiScale(gray)

print("No.of faces:",(len(faces)))

from google.colab.patches import cv2_imshow

!curl -o logo.jpg WhatsApp Image 2023-07-07 at 13.50.15.jpg
import cv2
img = cv2.imread('WhatsApp Image 2023-07-07 at 13.50.15.jpg', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

# diplay the faces in the image
import cv2
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x+w, y+h), (0, 255, 0), 2)
cv2_imshow(image)
cv2_waitKey(0)